### ISSUE TITLE
Running SkipSleep on a system with more than 1 valheim_server process does not work.

### ISSUE THREAD

**Issue by SirFrostingham** [RinseV/valheim-skipsleep#1]
One a single system, I may be running 3 servers at once, not just 1.

This mod does not work on Server B, due to this message on Server B's start up.

[Warning: BepInEx] Skipping [ModSkipSleepValheim 1.0.2] because of process filters (valheim.exe, valheim_server.exe)

Server A works with SkipSleep, Server B does not. Server A's Valheim process is "valheim_server.exe", Server B's process is "valheim_server3.exe".

Thanks for the great mod!

**Comment by SirFrostingham** [comment]
This mod does not work on Server B, due to this message on Server B's start up.

[Warning:   BepInEx] Skipping [ModSkipSleepValheim 1.0.2] because of process filters (valheim.exe, valheim_server.exe)

Server A works with SkipSleep, Server B does not. Server A's Valheim process is "valheim_server.exe", Server B's process is "valheim_server3.exe".

**Comment by SirFrostingham** [comment]
Here is the bug:
https://github.com/RinseV/valheim-skipsleep/blob/master/SkipSleep.cs

If you remove lines 12 and 13, the mod will work with any server process.

**Comment by RinseV** [comment]
Fixed as of [1.0.5](https://valheim.thunderstore.io/package/download/R1NS3/SkipSleep/1.0.5/), thanks again!
